"""more changes to how data is stored

Revision ID: 2bc2f84eef70
Revises: 92cd2552234b
Create Date: 2019-12-21 10:09:25.450533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc2f84eef70'
down_revision = '92cd2552234b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_paddle_hard', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_paddle_soft', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_is_paddle_hard'), 'user', ['is_paddle_hard'], unique=False)
    op.create_index(op.f('ix_user_is_paddle_soft'), 'user', ['is_paddle_soft'], unique=False)
    op.drop_index('ix_user_paddle_type', table_name='user')
    op.drop_column('user', 'paddle_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paddle_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_paddle_type', 'user', ['paddle_type'], unique=False)
    op.drop_index(op.f('ix_user_is_paddle_soft'), table_name='user')
    op.drop_index(op.f('ix_user_is_paddle_hard'), table_name='user')
    op.drop_column('user', 'is_paddle_soft')
    op.drop_column('user', 'is_paddle_hard')
    # ### end Alembic commands ###
