"""unique removal

Revision ID: 75db74e3f64d
Revises: a36cbc2b1bda
Create Date: 2019-12-17 20:03:25.808745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75db74e3f64d'
down_revision = 'a36cbc2b1bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_elo', table_name='user')
    op.create_index(op.f('ix_user_elo'), 'user', ['elo'], unique=False)
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.drop_index(op.f('ix_user_elo'), table_name='user')
    op.create_index('ix_user_elo', 'user', ['elo'], unique=True)
    # ### end Alembic commands ###
