"""created a challenge table

Revision ID: 92cd2552234b
Revises: 90b8b3c9b7fe
Create Date: 2019-12-19 21:52:14.696032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cd2552234b'
down_revision = '90b8b3c9b7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenger_id', sa.Integer(), nullable=True),
    sa.Column('challenged_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('resolved_match_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenged_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['challenger_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resolved_match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge')
    # ### end Alembic commands ###
